### ISSUE TITLE
Flarum encountered a boot error 

### ISSUE THREAD

**Issue by ASFAR2023** [AntoineFr/flarum-ext-money#46]
i get this error after activating Money plugin 
i use version [1.8.0]
```
POST https://*********************/api/settings

            Flarum encountered a boot error (Flarum\Extension\Exception\ExtensionBootError)<br />
            <b>Experienced an error while booting extension: Flarum Content Pages.

Error occurred while applying an extender of type: Flarum\Extend\ServiceProvider.</b><br />
            thrown in <b>/home/*********************/public_html/vendor/flarum/core/src/Extension/Extension.php</b> on line <b>143</b>

<pre>Error: Call to undefined function Dhtml\FlarumContentPages\Providers\getDetectedLocale() in /home/*********************/public_html/vendor/dhtml/flarum-content-pages/src/Providers/LocaleServiceProvider.php:24
Stack trace:
#0 /home/*********************/public_html/vendor/flarum/core/src/Foundation/Application.php(184): Dhtml\FlarumContentPages\Providers\LocaleServiceProvider->register()
#1 /home/*********************/public_html/vendor/flarum/core/src/Extend/ServiceProvider.php(41): Flarum\Foundation\Application->register()
#2 /home/*********************/public_html/vendor/flarum/core/src/Extension/Extension.php(141): Flarum\Extend\ServiceProvider->extend()
#3 /home/*********************/public_html/vendor/flarum/core/src/Extension/ExtensionManager.php(390): Flarum\Extension\Extension->extend()
#4 /home/*********************/public_html/vendor/flarum/core/src/Extension/ExtensionServiceProvider.php(31): Flarum\Extension\ExtensionManager->extend()
#5 [internal function]: Flarum\Extension\ExtensionServiceProvider->Flarum\Extension\{closure}()
#6 /home/*********************/public_html/vendor/flarum/core/src/Foundation/Application.php(329): call_user_func()
#7 /home/*********************/public_html/vendor/flarum/core/src/Foundation/Application.php(270): Flarum\Foundation\Application->fireAppCallbacks()
#8 /home/*********************/public_html/vendor/flarum/core/src/Foundation/InstalledSite.php(151): Flarum\Foundation\Application->boot()
#9 /home/*********************/public_html/vendor/flarum/core/src/Foundation/InstalledSite.php(82): Flarum\Foundation\InstalledSite->bootLaravel()
#10 /home/*********************/public_html/vendor/flarum/core/src/Http/Server.php(59): Flarum\Foundation\InstalledSite->bootApp()
#11 /home/*********************/public_html/vendor/flarum/core/src/Http/Server.php(36): Flarum\Http\Server->safelyBootAndGetHandler()
#12 /home/*********************/public_html/public/index.php(26): Flarum\Http\Server->listen()
#13 {main}

Next Flarum\Extension\Exception\ExtensionBootError: Experienced an error while booting extension: Flarum Content Pages.

Error occurred while applying an extender of type: Flarum\Extend\ServiceProvider. in /home/*********************/public_html/vendor/flarum/core/src/Extension/Extension.php:143
Stack trace:
#0 /home/*********************/public_html/vendor/flarum/core/src/Extension/ExtensionManager.php(390): Flarum\Extension\Extension->extend()
#1 /home/*********************/public_html/vendor/flarum/core/src/Extension/ExtensionServiceProvider.php(31): Flarum\Extension\ExtensionManager->extend()
#2 [internal function]: Flarum\Extension\ExtensionServiceProvider->Flarum\Extension\{closure}()
#3 /home/*********************/public_html/vendor/flarum/core/src/Foundation/Application.php(329): call_user_func()
#4 /home/*********************/public_html/vendor/flarum/core/src/Foundation/Application.php(270): Flarum\Foundation\Application->fireAppCallbacks()
#5 /home/*********************/public_html/vendor/flarum/core/src/Foundation/InstalledSite.php(151): Flarum\Foundation\Application->boot()
#6 /home/*********************/public_html/vendor/flarum/core/src/Foundation/InstalledSite.php(82): Flarum\Foundation\InstalledSite->bootLaravel()
#7 /home/*********************/public_html/vendor/flarum/core/src/Http/Server.php(59): Flarum\Foundation\InstalledSite->bootApp()
#8 /home/*********************/public_html/vendor/flarum/core/src/Http/Server.php(36): Flarum\Http\Server->safelyBootAndGetHandler()
#9 /home/*********************/public_html/public/index.php(26): Flarum\Http\Server->listen()
#10 {main}</pre>
```

**Comment by AntoineFr** [comment]
Hello @ASFAR2023 , your error doesn't seem to be related to my Money extension.
Based on the error message it was caused by "Flarum Content Pages". I found a related issue in this other extension: https://github.com/dhtml/flarum-content-pages/issues/1 , you should report it there.
